/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -p callback_proxy -- ../org.kde.nsplugins.CallBack.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "callback_proxy.h"

/*
 * Implementation of interface class OrgKdeNspluginsCallBackInterface
 */

OrgKdeNspluginsCallBackInterface::OrgKdeNspluginsCallBackInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeNspluginsCallBackInterface::~OrgKdeNspluginsCallBackInterface()
{
}


#include "callback_proxy.moc"
