# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6', 'Windows/Qt6', 'macOS/Qt6']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kbookmarks': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/solid': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kcompletion': 'Frameworks/6.24'
    'frameworks/ktextwidgets': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kdoctools': 'Frameworks/6.24'
    'frameworks/kfilemetadata': 'Frameworks/6.24'
    'frameworks/kcodecs': 'Frameworks/6.24'
    'frameworks/kuserfeedback': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'

 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
   'require':
    'frameworks/baloo': 'Frameworks/6.24'
    'libraries/baloo-widgets': '@same'
    'third-party/packagekit-qt': '@latest'

 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'Windows/Qt6', 'macOS/Qt6']
   'require':
    'network/kio-extras': '@same'

RuntimeDependencies:
 - 'on': ['Linux']
   'require':
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

Options:
 ctest-arguments: '--repeat until-pass:3'
 use-ccache: True
 require-passing-tests-on: ['Linux/Qt6', 'FreeBSD/Qt6']
