/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a callbackadaptor -c NsPluginsCallBackAdaptor -i plugin_part.h -l PluginPart -- org.kde.nsplugins.CallBack.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CALLBACKADAPTOR_H_226561151514943
#define CALLBACKADAPTOR_H_226561151514943

#include <QtCore/QObject>
#include <dbus/qdbus.h>
#include "plugin_part.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.nsplugins.CallBack
 */
class NsPluginsCallBackAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.nsplugins.CallBack")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.nsplugins.CallBack\" >\n"
"    <method name=\"requestURL\" >\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"target\" />\n"
"    </method>\n"
"    <method name=\"postURL\" >\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"target\" />\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"mime\" />\n"
"    </method>\n"
"    <method name=\"statusMessage\" >\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"msg\" />\n"
"    </method>\n"
"    <method name=\"evalJavaScript\" >\n"
"      <annotation value=\"true\" name=\"org.freedesktop.DBus.Method.NoReply\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\" />\n"
"      <arg direction=\"in\" type=\"s\" name=\"script\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    NsPluginsCallBackAdaptor(PluginPart *parent);
    virtual ~NsPluginsCallBackAdaptor();

    inline PluginPart *parent() const
    { return static_cast<PluginPart *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    Q_ASYNC void evalJavaScript(int id, const QString &script);
    Q_ASYNC void postURL(const QString &url, const QString &target, const QByteArray &data, const QString &mime);
    Q_ASYNC void requestURL(const QString &url, const QString &target);
    Q_ASYNC void statusMessage(const QString &msg);
Q_SIGNALS: // SIGNALS
};

#endif
