/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.nsplugins.NsPlugins.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "nspluginsadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class NsPluginsAdaptor
 */

NsPluginsAdaptor::NsPluginsAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

NsPluginsAdaptor::~NsPluginsAdaptor()
{
    // destructor
}

void NsPluginsAdaptor::evalJavaScript(int id, const QString &script)
{
    // handle method call org.kde.nsplugins.NsPlugins.evalJavaScript
    QMetaObject::invokeMethod(parent(), "evalJavaScript", Q_ARG(int, id), Q_ARG(QString, script));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->evalJavaScript(id, script);
}

void NsPluginsAdaptor::postURL(const QString &url, const QString &target, const QByteArray &data, const QString &mime)
{
    // handle method call org.kde.nsplugins.NsPlugins.postURL
    QMetaObject::invokeMethod(parent(), "postURL", Q_ARG(QString, url), Q_ARG(QString, target), Q_ARG(QByteArray, data), Q_ARG(QString, mime));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->postURL(url, target, data, mime);
}

void NsPluginsAdaptor::requestURL(const QString &url, const QString &target)
{
    // handle method call org.kde.nsplugins.NsPlugins.requestURL
    QMetaObject::invokeMethod(parent(), "requestURL", Q_ARG(QString, url), Q_ARG(QString, target));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->requestURL(url, target);
}

void NsPluginsAdaptor::statusMessage(const QString &msg)
{
    // handle method call org.kde.nsplugins.NsPlugins.statusMessage
    QMetaObject::invokeMethod(parent(), "statusMessage", Q_ARG(QString, msg));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->statusMessage(msg);
}


#include "nspluginsadaptor.moc"
