/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -m -p viewer_proxy -- viewer/org.kde.nsplugins.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "viewer_proxy.h"

/*
 * Implementation of interface class OrgKdeNspluginsClassInterface
 */

OrgKdeNspluginsClassInterface::OrgKdeNspluginsClassInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeNspluginsClassInterface::~OrgKdeNspluginsClassInterface()
{
}

/*
 * Implementation of interface class OrgKdeNspluginsInstanceInterface
 */

OrgKdeNspluginsInstanceInterface::OrgKdeNspluginsInstanceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeNspluginsInstanceInterface::~OrgKdeNspluginsInstanceInterface()
{
}

/*
 * Implementation of interface class OrgKdeNspluginsViewerInterface
 */

OrgKdeNspluginsViewerInterface::OrgKdeNspluginsViewerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeNspluginsViewerInterface::~OrgKdeNspluginsViewerInterface()
{
}


#include "viewer_proxy.moc"
