/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -p viewer_proxy -- viewer/org.kde.nsplugins.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "viewer_proxy.h"

/*
 * Implementation of interface class OrgKdeNspluginsClassInterface
 */

OrgKdeNspluginsClassInterface::OrgKdeNspluginsClassInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeNspluginsClassInterface::~OrgKdeNspluginsClassInterface()
{
}

/*
 * Implementation of interface class OrgKdeNspluginsInstanceInterface
 */

OrgKdeNspluginsInstanceInterface::OrgKdeNspluginsInstanceInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeNspluginsInstanceInterface::~OrgKdeNspluginsInstanceInterface()
{
}

/*
 * Implementation of interface class OrgKdeNspluginsViewerInterface
 */

OrgKdeNspluginsViewerInterface::OrgKdeNspluginsViewerInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeNspluginsViewerInterface::~OrgKdeNspluginsViewerInterface()
{
}


#include "viewer_proxy.moc"
