/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.FavIcon.xml
 *
 * The command line was:
 * dbusidl2cpp -m -a favicons_adaptor -c FavIconsAdaptor org.kde.FavIcon.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "favicons_adaptor.h"
#include "favicons.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class FavIconsAdaptor
 */

FavIconsAdaptor::FavIconsAdaptor(FavIconsModule *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

FavIconsAdaptor::~FavIconsAdaptor()
{
    // destructor
}

void FavIconsAdaptor::downloadHostIcon(const QString &url)
{
    // handle method call org.kde.FavIcon.downloadHostIcon
    static_cast<FavIconsModule *>(parent())->downloadHostIcon( KUrl(url) );
}

QString FavIconsAdaptor::iconForUrl(const QString &url)
{
    // handle method call org.kde.FavIcon.iconForUrl
    return static_cast<FavIconsModule *>(parent())->iconForUrl( KUrl(url) );
}

void FavIconsAdaptor::setIconForURL(const QString &url, const QString &iconURL)
{
    // handle method call org.kde.FavIcon.setIconForURL
    static_cast<FavIconsModule *>(parent())->setIconForURL( KUrl(url), KUrl(iconURL) );
}


#include "favicons_adaptor.moc"
