/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kdialog.ProgressDialog.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KDIALOGADAPTOR_H_214641149585043
#define KDIALOGADAPTOR_H_214641149585043

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kdialog.ProgressDialog
 */
class ProgressDialogAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kdialog.ProgressDialog")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kdialog.ProgressDialog\" >\n"
"    <property access=\"readwrite\" type=\"i\" name=\"maximum\" />\n"
"    <property access=\"readwrite\" type=\"i\" name=\"value\" />\n"
"    <property access=\"write\" type=\"s\" name=\"label\" />\n"
"    <property access=\"readwrite\" type=\"b\" name=\"autoClose\" />\n"
"    <method name=\"showCancelButton\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"value\" />\n"
"    </method>\n"
"    <method name=\"wasCancelled\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"close\" />\n"
"  </interface>\n"
        "")
public:
    ProgressDialogAdaptor(QObject *parent);
    virtual ~ProgressDialogAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool autoClose READ autoClose WRITE setAutoClose)
    bool autoClose() const;
    void setAutoClose(bool value);

    Q_PROPERTY(QString label WRITE setLabel)
    void setLabel(const QString &value);

    Q_PROPERTY(int maximum READ maximum WRITE setMaximum)
    int maximum() const;
    void setMaximum(int value);

    Q_PROPERTY(int value READ value WRITE setValue)
    int value() const;
    void setValue(int value);

public Q_SLOTS: // METHODS
    void close();
    void showCancelButton(bool value);
    bool wasCancelled();
Q_SIGNALS: // SIGNALS
};

#endif
