/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.kdialog.Progressdialog.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kdialogadaptor.h"
#include "kdialogadaptor.moc"

ProgressdialogAdaptor::ProgressdialogAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ProgressdialogAdaptor::~ProgressdialogAdaptor()
{
    // destructor
}

bool ProgressdialogAdaptor::autoClose()
{
    // handle method call org.kde.kdialog.Progressdialog.autoClose
    bool out0;
    QMetaObject::invokeMethod(parent(), "autoClose", Q_RETURN_ARG(bool, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->autoClose();
    return out0;
}

void ProgressdialogAdaptor::close()
{
    // handle method call org.kde.kdialog.Progressdialog.close
    QMetaObject::invokeMethod(parent(), "close");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->close();
}

int ProgressdialogAdaptor::maximum()
{
    // handle method call org.kde.kdialog.Progressdialog.maximum
    int out0;
    QMetaObject::invokeMethod(parent(), "maximum", Q_RETURN_ARG(int, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->maximum();
    return out0;
}

void ProgressdialogAdaptor::setAutoClose(bool value)
{
    // handle method call org.kde.kdialog.Progressdialog.setAutoClose
    QMetaObject::invokeMethod(parent(), "setAutoClose", Q_ARG(bool, value));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setAutoClose(value);
}

void ProgressdialogAdaptor::setLabel(const QString &label)
{
    // handle method call org.kde.kdialog.Progressdialog.setLabel
    QMetaObject::invokeMethod(parent(), "setLabel", Q_ARG(QString, label));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setLabel(label);
}

void ProgressdialogAdaptor::setMaximum(int maximum)
{
    // handle method call org.kde.kdialog.Progressdialog.setMaximum
    QMetaObject::invokeMethod(parent(), "setMaximum", Q_ARG(int, maximum));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setMaximum(maximum);
}

void ProgressdialogAdaptor::setValue(int value)
{
    // handle method call org.kde.kdialog.Progressdialog.setValue
    QMetaObject::invokeMethod(parent(), "setValue", Q_ARG(int, value));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setValue(value);
}

void ProgressdialogAdaptor::showCancelButton(bool value)
{
    // handle method call org.kde.kdialog.Progressdialog.showCancelButton
    QMetaObject::invokeMethod(parent(), "showCancelButton", Q_ARG(bool, value));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->showCancelButton(value);
}

int ProgressdialogAdaptor::value()
{
    // handle method call org.kde.kdialog.Progressdialog.value
    int out0;
    QMetaObject::invokeMethod(parent(), "value", Q_RETURN_ARG(int, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->value();
    return out0;
}

bool ProgressdialogAdaptor::wasCancelled()
{
    // handle method call org.kde.kdialog.Progressdialog.wasCancelled
    bool out0;
    QMetaObject::invokeMethod(parent(), "wasCancelled", Q_RETURN_ARG(bool, out0));

    // Alternative:
    //out0 = static_cast<YourObjectType *>(parent())->wasCancelled();
    return out0;
}

