/*
 * This file was generated by dbusidl2cpp version 0.4
 * when processing input file org.kde.kdialog.Progressdialog.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KDIALOGADAPTOR_H_298201149582612
#define KDIALOGADAPTOR_H_298201149582612

#include <QtCore/QObject>
#include <QtCore/QMetaObject>
#include <QtCore/QVariant>
#include <dbus/qdbus.h>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Adaptor class for interface org.kde.kdialog.Progressdialog
 */
class ProgressdialogAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kdialog.Progressdialog")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kdialog.Progressdialog\" >\n"
"    <method name=\"setMaximum\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"maximum\" />\n"
"    </method>\n"
"    <method name=\"maximum\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"setValue\" >\n"
"      <arg direction=\"in\" type=\"i\" name=\"value\" />\n"
"    </method>\n"
"    <method name=\"value\" >\n"
"      <arg direction=\"out\" type=\"i\" />\n"
"    </method>\n"
"    <method name=\"setLabel\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"label\" />\n"
"    </method>\n"
"    <method name=\"showCancelButton\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"value\" />\n"
"    </method>\n"
"    <method name=\"wasCancelled\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"setAutoClose\" >\n"
"      <arg direction=\"in\" type=\"b\" name=\"value\" />\n"
"    </method>\n"
"    <method name=\"autoClose\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"close\" />\n"
"  </interface>\n"
        "")
public:
    ProgressdialogAdaptor(QObject *parent);
    virtual ~ProgressdialogAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool autoClose();
    void close();
    int maximum();
    void setAutoClose(bool value);
    void setLabel(const QString &label);
    void setMaximum(int maximum);
    void setValue(int value);
    void showCancelButton(bool value);
    int value();
    bool wasCancelled();
Q_SIGNALS: // SIGNALS
};

#endif

