/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a konq_historymgr_adaptor -c KonqHistoryManagerAdaptor -i konq_historymgr.h -l KonqHistoryManager -- org.kde.libkonq.KonqHistoryManager.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KONQ_HISTORYMGR_ADAPTOR_H_73691150740458
#define KONQ_HISTORYMGR_ADAPTOR_H_73691150740458

#include <QtCore/QObject>
#include <dbus/qdbus.h>
#include "konq_historymgr.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.libkonq.KonqHistoryManager
 */
class KonqHistoryManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.libkonq.KonqHistoryManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.libkonq.KonqHistoryManager\" >\n"
"    <signal name=\"notifyHistoryEntry\" >\n"
"      <arg direction=\"out\" type=\"ay\" name=\"historyEntry\" />\n"
"    </signal>\n"
"    <signal name=\"notifyMaxCount\" >\n"
"      <arg direction=\"out\" type=\"i\" name=\"count\" />\n"
"    </signal>\n"
"    <signal name=\"notifyMaxAge\" >\n"
"      <arg direction=\"out\" type=\"i\" name=\"days\" />\n"
"    </signal>\n"
"    <signal name=\"notifyClear\" />\n"
"    <signal name=\"notifyRemove\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"url\" />\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    KonqHistoryManagerAdaptor(KonqHistoryManager *parent);
    virtual ~KonqHistoryManagerAdaptor();

    inline KonqHistoryManager *parent() const
    { return static_cast<KonqHistoryManager *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void notifyClear();
    void notifyHistoryEntry(const QByteArray &historyEntry);
    void notifyMaxAge(int days);
    void notifyMaxCount(int count);
    void notifyRemove(const QString &url);
};

#endif
