/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a konq_historymgr_adaptor -c KonqHistoryManagerAdaptor -i konq_historymgr.h -l KonqHistoryManager -- org.kde.libkonq.KonqHistoryManager.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "konq_historymgr_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KonqHistoryManagerAdaptor
 */

KonqHistoryManagerAdaptor::KonqHistoryManagerAdaptor(KonqHistoryManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KonqHistoryManagerAdaptor::~KonqHistoryManagerAdaptor()
{
    // destructor
}


#include "konq_historymgr_adaptor.moc"
