/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a konq_undoadaptor -c KonqUndoManagerAdaptor -l KonqUndoManager -i konq_undo.h -- org.kde.libkonq.UndoManager.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef KONQ_UNDOADAPTOR_H_188381151072115
#define KONQ_UNDOADAPTOR_H_188381151072115

#include <QtCore/QObject>
#include <dbus/qdbus.h>
#include "konq_undo.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.libkonq.UndoManager
 */
class KonqUndoManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.libkonq.UndoManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.libkonq.UndoManager\" >\n"
"    <method name=\"get\" >\n"
"      <arg direction=\"out\" type=\"ay\" name=\"commands\" />\n"
"    </method>\n"
"    <signal name=\"lock\" />\n"
"    <signal name=\"pop\" />\n"
"    <signal name=\"push\" >\n"
"      <arg direction=\"out\" type=\"ay\" name=\"command\" />\n"
"    </signal>\n"
"    <signal name=\"unlock\" />\n"
"  </interface>\n"
        "")
public:
    KonqUndoManagerAdaptor(KonqUndoManager *parent);
    virtual ~KonqUndoManagerAdaptor();

    inline KonqUndoManager *parent() const
    { return static_cast<KonqUndoManager *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QByteArray get();
Q_SIGNALS: // SIGNALS
    void lock();
    void pop();
    void push(const QByteArray &command);
    void unlock();
};

#endif
