/*
 * This file was generated by dbusidl2cpp version 0.6
 * Command line was: dbusidl2cpp -m -a konq_undoadaptor -c KonqUndoManagerAdaptor -l KonqUndoManager -i konq_undo.h -- org.kde.libkonq.UndoManager.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "konq_undoadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KonqUndoManagerAdaptor
 */

KonqUndoManagerAdaptor::KonqUndoManagerAdaptor(KonqUndoManager *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KonqUndoManagerAdaptor::~KonqUndoManagerAdaptor()
{
    // destructor
}

QByteArray KonqUndoManagerAdaptor::get()
{
    // handle method call org.kde.libkonq.UndoManager.get
    QByteArray commands;
    commands = parent()->get();
    return commands;
}


#include "konq_undoadaptor.moc"
