/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.libkonq.UndoManager.xml
 * The command line was: 
 * dbusidl2cpp -m -a konq_undoadaptor -c KonqUndoManagerAdaptor org.kde.libkonq.UndoManager.xml 
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "konq_undoadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KonqUndoManagerAdaptor
 */

KonqUndoManagerAdaptor::KonqUndoManagerAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KonqUndoManagerAdaptor::~KonqUndoManagerAdaptor()
{
    // destructor
}

QByteArray KonqUndoManagerAdaptor::get()
{
    // handle method call org.kde.libkonq.UndoManager.get
    QByteArray commands;
    QMetaObject::invokeMethod(parent(), "get", Q_RETURN_ARG(QByteArray, commands));

    // Alternative:
    //commands = static_cast<YourObjectType *>(parent())->get();
    return commands;
}


#include "konq_undoadaptor.moc"
