/*
 * This file was generated by dbusidl2cpp version 0.3
 * when processing input file org.kde.KIO.UIServer.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "uiserveriface.h"

/*
 * Implementation of interface class OrgKdeKIOUIServerInterface
 */

OrgKdeKIOUIServerInterface::OrgKdeKIOUIServerInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeKIOUIServerInterface::~OrgKdeKIOUIServerInterface()
{
}

#include "uiserveriface.moc"
